services:
  ngingx-reverse-proxy:
    image: nginx:alpine
    container_name: nginxrvpro
    ports: 
      - 80:80 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - traffic_lights  

  red-app:
    image: galnewman/lights:red-v1.0
    container_name: red-app
    # ports:
      # - 3000:80
    networks:
      - traffic_lights


  green-app:
    image: galnewman/lights:green-v1.0
    container_name: green-app
    # ports:
    #   - 5000:80
    networks:
      - traffic_lights
  yellow-app:
    image: galnewman/lights:yellow-v1.0
    container_name: yellow-app
    # ports:
    #   - 4000:80
    networks:
      - traffic_lights

networks:
  traffic_lights:
    driver: bridge




#volumes: